apm install auto-detect-indentation
apm install autoclose-html
apm install autocomplete-paths
apm install cursor-history
apm install docblockr
apm install editorconfig
apm install emmet
apm install git-time-machine
apm install goto-last-edit
apm install highlight-selected
apm install lazy-motion
apm install linter
apm install linter-eslint
apm install linter-jsonlint
apm install move-panes
apm install open-recent
apm install open-this
apm install pane-by-type
apm install project-find-navigation
apm install react
apm install related
apm install relative-numbers
apm install rest-client
apm install set-syntax
apm install terminal-panel
apm install vim-mode-plus
apm install vim-mode-plus-ex-mode
apm install vim-mode-plus-subword-movement
